### ISSUE TITLE
MRO Exception

### ISSUE THREAD

**Issue by lucemia** [koendewit/django-direct-cloud-upload#2]
The sample code: 

```
from direct_cloud_upload import DdcuAdminMixin

class EbookAdmin(admin.ModelAdmin, DdcuAdminMixin):
    form = EbookForm
```

will raise MRO Exception

```
TypeError: Cannot create a consistent method resolution
order (MRO) for bases ModelAdmin, DdcuAdminMixin
```

Due to DdcuAdminMixin itself is subclass of ModeAdmin.

https://github.com/koendewit/django-direct-cloud-upload/blob/2dbc12be87f0dc048671e88adbeea6f7179fcc7f/direct_cloud_upload/admin.py#L3-L6

**Comment by koendewit** [comment]
You are right @lucemia , thanks for letting me know! Fixed in  9bca301.
