### ISSUE TITLE
Ongoing maintenance and joining django-gcp

### ISSUE THREAD

**Issue by thclark** [koendewit/django-direct-cloud-upload#3]
Hi @keondewit, thanks for a good library!

I've been building [django-gcp](https://django-gcp.readthedocs.io/en/latest/index.html) to package together and maintain all things django on GCP. We have an [issue there to enable direct to cloud uploads](https://github.com/octue/django-gcp/issues/22).

I'm wondering what your intentions are with this package? If you're actively working with django on GCP for the foreseeable, and maintaining this package that's amazing. However, if maintenance for this is something you'd like to offload or join with a wider effort, it'd be great to fold it into the django-gcp project. 

Any thoughts?

Thanks,

Tom

**Comment by koendewit** [comment]
Hi Tom,

django-gcp looks nice !  I'll definitely have a better look in the near future, maybe I'll use it in my own projects.

I will definitely continue maintaining this package, it is in use by a number of applications. But you are free to copy parts of the code to django-gcp!

Koen.

**Comment by thclark** [comment]
Thanks Koen! :)
